# Declare variables to be passed into your templates.

replicaCount: 1

#helm doesnt interact with docker hub. K8S does it, only the repo info is passed on here.
image:
  repository: dishadgithub/node-application
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.0.2"

service:
  type: ClusterIP
  # service listens on this port(eg: if a Pod(pod2) within the cluster sends a network request to my-service on port 80)
  port: 80
  # service forwards the request to targetport on which the app is running(on pod1)
  targetPort: 3000

#for loadbalancer setup, using nginx as loadbalancer

#  Ingress controller (the component responsible for managing Ingress resources) should be nginx. 
# This means that nginx will be used to route traffic from outside the cluster to services within the cluster.
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: node-app.local
      paths:
        - path: /
          pathType: Prefix