name: node workflow

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  node-application:
    runs-on: ubuntu-latest

    steps:
    #copy of your repository at the GitHub runner
    - name: Check Out Repo
      uses: actions/checkout@v2

    #support for building multi-platform images
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    #docker executes inside the my-node-app container
    #-f flag causes curl to fail if the HTTP request doesn't return a success status code
    - name: Dockerize node
      run: |
        docker build -f ./node/Dockerfile -t my-node-app .
        docker images
        docker run -d --name my-node-app -p 3000:3000 my-node-app
        docker logs my-node-app
        sleep 10  # wait for the application to start
        docker exec my-node-app curl -f http://localhost:3000

      - name: Tag Docker image
        run: |
          docker tag my-node-app dishadgithub/node-application:0.0.2

      - name: Push image to Docker Hub
        run: |
          docker push dishadgithub/node-application:0.0.2
