name: node workflow

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  node-application:
    runs-on: ubuntu-latest

    #copy of your repository at the GitHub runner
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

    #support for building multi-platform images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    #-f flag causes curl to fail if the HTTP request doesn't return a success status code
    # docker executes inside the my-node-app container
      - name: Dockerize node
        run: |
          docker build -f ./node/Dockerfile -t my-node-app .
          docker images
          docker run -d --name my-node-app -p 3000:3000 my-node-app
          docker logs my-node-app
          sleep 10
          docker exec my-node-app curl -f http://localhost:3000
          docker tag my-node-app dishadgithub/node-application:0.0.2
          docker push dishadgithub/node-application:0.0.2

      - name: Install Minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube /usr/local/bin/minikube
          sudo apt-get update && sudo apt-get install conntrack         #required for minikube kub version to start
          sudo minikube start --driver=none --kubernetes-version=v1.21.0
          sudo mkdir -p /home/runner/.kube/
          sudo cp /root/.kube/config /home/runner/.kube/config
          sudo chown runner:runner /home/runner/.kube/config
          sudo cp -r /root/.minikube /home/runner/
          sudo chown -R runner:runner /home/runner/.minikube/
          sudo sed -i 's|/root/.minikube|/home/runner/.minikube|g' /home/runner/.kube/config
          echo $USER           #runner is the profile used
          sudo minikube status


      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          

      - name: Install NGINX Ingress Controller
        run: |
          kubectl describe nodes
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update
          helm install nginx-ingress ingress-nginx/ingress-nginx --set controller.publishService.enabled=true

      - name: Deploy Application
        run: |
          helm upgrade --install node ./node/helm-node --set ingress.enabled=true --set ingress.hosts[0].host=node-app.local
          kubectl get nodes


